const express = require('express')
const router = express.Router()
const adminController = require('../../controllers/admin-controller')
const upload = require('../../middleware/multer')

router.get('/restaurants/:id/edit', adminController.getEditRestaurant)
router.delete('/categories/:id', adminController.deleteCategory)
router.get('/categories/:id', adminController.getCategories)
router.put('/categories/:id', adminController.putCategory)
router.get('/restaurants/create', adminController.getCreateRestaurant)
router.put('/restaurants/:id', upload.single('image'), adminController.putRestaurant)
router.delete('/restaurants/:id', adminController.deleteRestaurant)
router.patch('/users/:id', adminController.patchUserRole)
router.post('/categories', adminController.postCategory)
router.get('/categories', adminController.getCategories)
router.get('/restaurants', adminController.getRestaurants)
router.post('/restaurants', upload.single('image'), adminController.postCreateRestaurant)
router.get('/users', adminController.getUsers)
router.use('/', (req, res) => res.redirect('/admin/restaurants'))

module.exports = router
